# Generated by Django 5.2.5 on 2025-08-31 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('clave', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'MetodoAnalitico',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadARevisar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoElemento', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'PropiedadesARevisar',
            },
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'UnidadDeMedida',
            },
        ),
        migrations.CreateModel(
            name='KitDeReactivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeRecepcion', models.DateTimeField(auto_now_add=True)),
                ('estadoDelProducto', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('laboratorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits_de_reactivos', to='lab.laboratorio')),
            ],
            options={
                'verbose_name_plural': 'KitDeReactivos',
            },
        ),
        migrations.CreateModel(
            name='ProgramaLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='lab.laboratorio')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios', to='lab.programa')),
            ],
            options={
                'verbose_name_plural': 'ProgramaLaboratorio',
            },
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('instrumento_seleccionado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_instrumento_seleccionado_id', to='lab.instrumento')),
                ('metodo_analitico_seleccionado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_metodo_analitico_seleccionado_id', to='lab.metodoanalitico')),
                ('programa_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='lab.programa')),
                ('reactivo_seleccionado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_reactivo_seleccionado_id', to='lab.reactivo')),
                ('unidad_de_medida_seleccionado_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_unidad_de_medida_seleccionado_id', to='lab.unidaddemedida')),
            ],
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('laboratorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos', to='lab.laboratorio')),
                ('prueba_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos', to='lab.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='UserLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='lab.laboratorio')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserLaboratorio',
            },
        ),
        migrations.CreateModel(
            name='LaboratorioPruebaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_prueba_config_instrumento_id', to='lab.instrumento')),
                ('laboratorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios', to='lab.laboratorio')),
                ('metodo_analitico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_prueba_config_metodo_analitico_id', to='lab.metodoanalitico')),
                ('prueba_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='lab.prueba')),
                ('reactivo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_prueba_config_pruebas_reactivo_id', to='lab.reactivo')),
                ('unidad_de_medida_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_prueba_config_pruebas_unidad_de_medida_id', to='lab.unidaddemedida')),
            ],
            options={
                'verbose_name_plural': 'LaboratorioPruebaConfig',
                'constraints': [models.UniqueConstraint(fields=('laboratorio_id', 'prueba_id'), name='uq_laboratorio_prueba')],
            },
        ),
    ]
