# Generated by Django 5.2.5 on 2025-08-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='contacto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
