# Generated by Django 5.2.5 on 2025-09-02 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedadarevisar',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Propiedades a Revisar'},
        ),
        migrations.AddField(
            model_name='propiedadarevisar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedadarevisar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propiedadarevisar',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pendiente'), (1, 'Aprobado'), (2, 'Rechazado')], default=0),
        ),
        migrations.AlterField(
            model_name='propiedadarevisar',
            name='tipoElemento',
            field=models.CharField(choices=[('instrumento', 'Instrumento'), ('metodo', 'Método Analítico'), ('reactivo', 'Reactivo'), ('unidad', 'Unidad')], max_length=50),
        ),
    ]
