# Generated by Django 5.2.5 on 2025-09-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_propiedadarevisar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='edicion_hasta_dia',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='override_edicion_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='override_edicion_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratoriopruebaconfig',
            name='bloqueada',
            field=models.BooleanField(default=False),
        ),
    ]
