# Generated by Django 5.2.5 on 2025-08-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_laboratorio_contacto_laboratorio_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='clave',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='contacto',
            field=models.CharField(blank=True),
        ),
    ]
