# Generated by Django 5.2.5 on 2025-08-21 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('metodo_analitco', models.CharField(max_length=255)),
                ('instrumento', models.CharField(max_length=255)),
                ('reactivo', models.CharField(max_length=255)),
                ('unidad_de_medida', models.CharField(max_length=255)),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='lab.programa')),
            ],
        ),
    ]
