# Generated by Django 5.2.5 on 2025-08-21 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='metodo_analitco',
        ),
        migrations.AlterField(
            model_name='prueba',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='lab.instrumento'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='metodo_analitico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='lab.metodoanalitico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prueba',
            name='reactivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='lab.reactivo'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='unidad_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='lab.unidaddemedida'),
        ),
    ]
