# Generated by Django 5.2.5 on 2025-09-22 14:59

import lab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_laboratorio_edicion_hasta_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato',
            name='mes',
            field=models.DateField(default=lab.models.first_day_of_current_month),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Configuración'), (2, 'Registro'), (3, 'Consulta')], default=1),
        ),
        migrations.AddConstraint(
            model_name='dato',
            constraint=models.UniqueConstraint(fields=('laboratorio_id', 'prueba_id', 'mes'), name='uq_dato_lab_prueba_mes'),
        ),
    ]
