# Generated by Django 5.2.5 on 2025-10-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_dato_mes_laboratorio_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='corte_captura_dia',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='override_captura_activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='override_captura_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes (YYYY-MM-01)')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='reportes/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='lab.laboratorio')),
            ],
        ),
    ]
