# Generated by Django 5.2.5 on 2025-08-26 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0004_instrumento_metodoanalitico_reactivo_unidaddemedida_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laboratorio",
            name="contacto",
        ),
        migrations.RemoveField(
            model_name="laboratorio",
            name="correo",
        ),
        migrations.CreateModel(
            name="user_laboratorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laboratorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="lab.laboratorio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laboratorios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
