# Generated by Django 5.2.5 on 2025-10-30 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_laboratorio_corte_captura_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='estado',
            field=models.CharField(choices=[('trabajando', 'Trabajando'), ('completado', 'Completado')], default='trabajando', max_length=12),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de referencia mostrada en tabla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='programas',
            field=models.ManyToManyField(blank=True, related_name='reportes', to='lab.programa'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='pruebas',
            field=models.ManyToManyField(blank=True, related_name='reportes', to='lab.prueba'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tipo',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='reportes/%Y/%m/'),
        ),
        migrations.AddConstraint(
            model_name='reporte',
            constraint=models.UniqueConstraint(fields=('laboratorio', 'tipo', 'mes'), name='uq_reporte_lab_tipo_mes'),
        ),
        migrations.AddConstraint(
            model_name='reporte',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mes__day', 1), ('mes__month', 1), ('tipo', 'anual')), models.Q(('tipo', 'anual'), _negated=True), _connector='OR'), name='ck_reporte_anual_mes_enero'),
        ),
        migrations.AddConstraint(
            model_name='reporte',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('archivo__isnull', False), ('estado', 'completado')), models.Q(('estado', 'completado'), _negated=True), _connector='OR'), name='ck_reporte_completado_con_archivo'),
        ),
    ]
