# Generated by Django 5.2.5 on 2025-08-27 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_remove_laboratorio_contacto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MetodosAnaliticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadesARevisar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoElemento', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reactivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='instrumento',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='metodo_analitico',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='reactivo',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='unidad_de_medida',
        ),
        migrations.AlterField(
            model_name='prueba',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='lab.programa'),
        ),
        migrations.AlterField(
            model_name='user_laboratorio',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='lab.laboratorio'),
        ),
        migrations.AlterField(
            model_name='user_laboratorio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Dato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos', to='lab.laboratorio')),
                ('prueba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datos', to='lab.prueba')),
            ],
        ),
        migrations.CreateModel(
            name='KitDeReactivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaDeRecepcion', models.DateTimeField(auto_now_add=True)),
                ('estadoDelProducto', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kits_de_reactivos', to='lab.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='programa_laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas', to='lab.laboratorio')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios', to='lab.programa')),
            ],
        ),
        migrations.DeleteModel(
            name='Instrumento',
        ),
        migrations.DeleteModel(
            name='MetodoAnalitico',
        ),
        migrations.DeleteModel(
            name='Reactivo',
        ),
        migrations.DeleteModel(
            name='UnidadDeMedida',
        ),
    ]
