# Generated by Django 5.2.5 on 2025-11-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_reporte_estado_reporte_fecha_reporte_programas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadarevisar',
            name='propuesto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='propuestas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='propiedadarevisar',
            index=models.Index(fields=['status'], name='lab_propied_status_9a8275_idx'),
        ),
        migrations.AddIndex(
            model_name='propiedadarevisar',
            index=models.Index(fields=['propuesto_por'], name='lab_propied_propues_d23f79_idx'),
        ),
    ]
