# Generated by Django 5.2.5 on 2025-08-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_instrumentos_metodosanaliticos_propiedadesarevisar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadesdemedida',
            name='default',
        ),
        migrations.AddField(
            model_name='instrumentos',
            name='defaultEnPruebas',
            field=models.ManyToManyField(blank=True, related_name='instrumentos', to='lab.prueba'),
        ),
        migrations.AddField(
            model_name='metodosanaliticos',
            name='defaultEnPruebas',
            field=models.ManyToManyField(blank=True, related_name='modelos_analíticos', to='lab.prueba'),
        ),
        migrations.AddField(
            model_name='reactivos',
            name='defaultEnPruebas',
            field=models.ManyToManyField(blank=True, related_name='reactivos', to='lab.prueba'),
        ),
        migrations.AddField(
            model_name='unidadesdemedida',
            name='defaultEnPruebas',
            field=models.ManyToManyField(blank=True, related_name='unidades_de_medida', to='lab.prueba'),
        ),
    ]
