# Generated by Django 5.2.5 on 2025-08-27 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_remove_unidadesdemedida_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadesdemedida',
            name='defaultEnPruebas',
        ),
        migrations.AddField(
            model_name='prueba',
            name='instrumento_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_default', to='lab.instrumentos'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='metodo_analitico_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_default', to='lab.metodosanaliticos'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='reactivo_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_default', to='lab.reactivos'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='unidad_de_medida_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='lab.unidadesdemedida'),
        ),
    ]
