# Generated by Django 5.2.5 on 2025-08-28 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_remove_unidadesdemedida_defaultenpruebas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PropiedadARevisar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoElemento', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reactivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='UnidadesDeMedida',
            new_name='UnidadDeMedida',
        ),
        migrations.RemoveField(
            model_name='instrumentos',
            name='defaultEnPruebas',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='instrumento_default',
        ),
        migrations.RemoveField(
            model_name='metodosanaliticos',
            name='defaultEnPruebas',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='metodo_analitico_default',
        ),
        migrations.DeleteModel(
            name='PropiedadesARevisar',
        ),
        migrations.RemoveField(
            model_name='reactivos',
            name='defaultEnPruebas',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='reactivo_default',
        ),
        migrations.RenameField(
            model_name='dato',
            old_name='laboratorio',
            new_name='laboratorio_id',
        ),
        migrations.RenameField(
            model_name='dato',
            old_name='prueba',
            new_name='prueba_id',
        ),
        migrations.RenameField(
            model_name='kitdereactivos',
            old_name='laboratorio',
            new_name='laboratorio_id',
        ),
        migrations.RenameField(
            model_name='programa_laboratorio',
            old_name='laboratorio',
            new_name='laboratorio_id',
        ),
        migrations.RenameField(
            model_name='programa_laboratorio',
            old_name='programa',
            new_name='programa_id',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='programa',
            new_name='programa_id',
        ),
        migrations.RenameField(
            model_name='prueba',
            old_name='unidad_de_medida_default',
            new_name='unidad_de_medida_default_id',
        ),
        migrations.RenameField(
            model_name='user_laboratorio',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='prueba',
            name='instrumento_default_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_default', to='lab.instrumento'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='metodo_analitico_default_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_default', to='lab.metodoanalitico'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='reactivo_default_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_default', to='lab.reactivo'),
        ),
        migrations.DeleteModel(
            name='Instrumentos',
        ),
        migrations.DeleteModel(
            name='MetodosAnaliticos',
        ),
        migrations.DeleteModel(
            name='Reactivos',
        ),
    ]
