# Generated by Django 5.2.5 on 2025-11-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_propiedadarevisar_resolved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedadarevisar',
            name='moderation_nonce',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
