# Generated by Django 5.2.5 on 2025-08-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_instrumento_metodoanalitico_propiedadarevisar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumento',
            name='default',
        ),
        migrations.RemoveField(
            model_name='metodoanalitico',
            name='default',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='instrumento_default_id',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='metodo_analitico_default_id',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='reactivo_default_id',
        ),
        migrations.RemoveField(
            model_name='prueba',
            name='unidad_de_medida_default_id',
        ),
        migrations.RemoveField(
            model_name='reactivo',
            name='default',
        ),
        migrations.AddField(
            model_name='prueba',
            name='instrumento_seleccionado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_instrumento_seleccionado', to='lab.instrumento'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='metodo_analitico_seleccionado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_metodo_analitico_seleccionado', to='lab.metodoanalitico'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='reactivo_seleccionado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_reactivo_seleccionado', to='lab.reactivo'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='unidad_de_medida_seleccionado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_unidad_de_medida_seleccionado', to='lab.unidaddemedida'),
        ),
    ]
