# Generated by Django 5.2.5 on 2025-08-31 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_remove_instrumento_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='instrumento_seleccionado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_instrumento_seleccionado_id', to='lab.instrumento'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='metodo_analitico_seleccionado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_metodo_analitico_seleccionado_id', to='lab.metodoanalitico'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='reactivo_seleccionado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_reactivo_seleccionado_id', to='lab.reactivo'),
        ),
        migrations.AlterField(
            model_name='prueba',
            name='unidad_de_medida_seleccionado_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pruebas_unidad_de_medida_seleccionado_id', to='lab.unidaddemedida'),
        ),
        migrations.CreateModel(
            name='laboratorio_prueba_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_prueba_config_instrumento_id', to='lab.instrumento')),
                ('laboratorio_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laboratorios', to='lab.laboratorio')),
                ('metodo_analitico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_prueba_config_metodo_analitico_id', to='lab.metodoanalitico')),
                ('prueba_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pruebas', to='lab.prueba')),
                ('reactivo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_prueba_config_pruebas_reactivo_id', to='lab.reactivo')),
                ('unidad_de_medida_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratorio_prueba_config_pruebas_unidad_de_medida_id', to='lab.unidaddemedida')),
            ],
        ),
    ]
